spring:
  profiles:
    active: dev
  flyway:
    locations: "classpath:db"

telegram:
  token:

management:
  endpoint:
    health:
      show-details: always
  server:
    port: 8082
  endpoints:
    web:
      exposure:
        include: "*"
